extends Node

const PLAYER_COLLISION_LAYER= 1
const GRID_COLLISION_LAYER= 2
const TERRAIN_COLLISION_LAYER= 4
const PROJECTILE_COLLISION_LAYER= 8
const PHYSICAL_OBJECTS_COLLISION_LAYER= 16
const PERIPHERAL_GRID_ENTITIES_COLLISION_LAYER= 32
const WORLD_ITEM_COLLISION_LAYER= 64

var player: Player
var game: Game
